# Mantra Testnet (mantra-dukong)
# Last updated: 2025-06-06T14:50:58+0000
# Chain ID: mantra-dukong
# Deployer: mantra1cc0jfcd3rv3d36g6m575mdk8p2nmdjgnaf7ngq
# Block height: 6032195

[mantra-dukong]
chain_id = "mantra-dukong"
deployer = "mantra1cc0jfcd3rv3d36g6m575mdk8p2nmdjgnaf7ngq"

[mantra-dukong.epoch_manager]
code_id = 822
version = "1.0.0"
address = "mantra1kz0gcs8n0qa9rje5zdrlwqccxlwu8zttzmdtxhdq0jpk3efjs37qr4s2sv"

[mantra-dukong.farm_manager]
code_id = 823
version = "1.0.0"
address = "mantra1h3ypj6fhpn4tegj0flhx42j5c4jejq45dypyjy7wdpr268amh5ssa4nnzf"

[mantra-dukong.fee_collector]
code_id = 824
version = "1.0.0"
address = "mantra1ze9rccntuvd37gs5fv8ddtjtaytaj4944zn3mksdnne8zyntjmgsg9syav"

[mantra-dukong.pool_manager]
code_id = 825
version = "1.3.0"
address = "mantra1vwj600jud78djej7ttq44dktu4wr3t2yrrsjgmld8v3jq8mud68q5w7455"
# address = "mantra1us7rryvauhpe82fff0t6gjthdraqmtm5gw8c808f6eqzuxmulacqzkzdal"

[mantra-dukong.skip_entry_point]
code_id = 939
version = "1.0.0"
address = "mantra13spfalxdxgn0xyd87zqv3af2cmng5xugk0y64xhh0rhnnwqx8fks8netgq"

[mantra-dukong.skip_ibc_hooks_adapter]
code_id = 940
version = "1.0.0"
address = "mantra1yzl27sewa2447vtvnp00r02fca8sw3vyptysmyp9jnduky5lv8wqfqlkpy"

[mantra-dukong.skip_mantra_dex_adapter]
code_id = 941
version = "1.0.0"
address = "mantra1s4sej56myvcgudtp6hrlgaxrsr8fwycwtetwrhsl933tppk8ve2susgk7h"
