# Mantra Testnet (mantra-dukong-1)
# Last updated: 2024-11-14T15:26:36+0000
# Chain ID: mantra-dukong-1
# Deployer: mantra1x5nk33zpglp4ge6q9a8xx3zceqf4g8nvaggjmc
# Block height: 923089

[mantra-dukong]
chain_id = "mantra-dukong-1"
deployer = "mantra1x5nk33zpglp4ge6q9a8xx3zceqf4g8nvaggjmc"

[mantra-dukong.epoch_manager]
code_id = 90
version = "1.0.0"
address = "mantra1kz0gcs8n0qa9rje5zdrlwqccxlwu8zttzmdtxhdq0jpk3efjs37qr4s2sv"

[mantra-dukong.farm_manager]
code_id = 109
version = "1.0.0"
address = "mantra1h3ypj6fhpn4tegj0flhx42j5c4jejq45dypyjy7wdpr268amh5ssa4nnzf"

[mantra-dukong.fee_collector]
code_id = 54
version = "1.0.0"
address = "mantra1ze9rccntuvd37gs5fv8ddtjtaytaj4944zn3mksdnne8zyntjmgsg9syav"

[mantra-dukong.pool_manager]
code_id = 532
version = "1.2.0"
address = "mantra1vwj600jud78djej7ttq44dktu4wr3t2yrrsjgmld8v3jq8mud68q5w7455"
