[mantra-dukong]
network_name = "mantra-dukong"
chain_id = "mantra-dukong-1"
default_rpc = "https://rpc.dukong.mantrachain.io:443"
default_gas_price = 0.01
default_gas_adjustment = 1.5
native_denom = "uom" 