[mantra-dukong]
network_name = "mantra-dukong"
network_id = "mantra-dukong-1"
default_rpc = "https://rpc.dukong.mantrachain.io/"
default_gas_price = 0.025
default_gas_adjustment = 1.3
native_denom = "uom" 